### ISSUE TITLE
How to use other *.prm file ?

### ISSUE THREAD

**Issue by nyue** [conservation-laws/ryujin#3]
Whenever I run ryujin, it creates a cylinder-parameter.prm file

How do I tell ryujin to use another *.prm file e.g. the file euler-cylinder-3d.prm

Cheers

**Comment by tamiko** [comment]
If you just run the executable without a parameter it will read in `ryujin.prm` and use that parameter file. You can specify an alternative parameter file as first argument to the executable, for example
```
 $ ./ryujin ../../prm/euler-cylinder-3d.prm
```

Note that the program will always write the current set of parameters (together with a ton of log files) to a file called `<basename>-parameter.prm`. So `cylinder-parameter.prm` just documents what parameters had been chosen to run the "cylinder" configuration, but the actual configuration happens in `ryujin.prm` or by specifying a file on the command line.

Hope this clarifies it a bit!
