### ISSUE TITLE
Settings for machine with limited RAM (64Gig) ?

### ISSUE THREAD

**Issue by nyue** [conservation-laws/ryujin#4]
I have access to a small machine with CentOS 7 4 cores and 64Gig RAM

When I tried running the example euler-cylinder-3d.prm it ran out of memory.

I am wondering what settings in the PRM file allow one to do test run on smaller machines ?

Cheers

**Comment by tamiko** [comment]
For the 3D cylinder you would need to reduce the refinement a bit. The parameter file currently has `set mesh refinement = 6`, which is billions of degrees of freedom. What about you start with `3` and then try `4`?

**Comment by nyue** [comment]
Great. I will start with 3 and work my way up.
